"""add github accounts

Revision ID: 76f6372ed049
Revises: 0aa06cbe640c
Create Date: 2026-08-08 00:00:30.178431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f6372ed049'
down_revision = '0aa06cbe640c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_user_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(length=80), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(length=32), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('github_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_accounts_github_user_id'), ['github_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_github_accounts_github_username'), ['github_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_accounts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_github_accounts_github_username'))
        batch_op.drop_index(batch_op.f('ix_github_accounts_github_user_id'))

    op.drop_table('github_accounts')
    # ### end Alembic commands ###
